<?php
session_start();
include('connection.php');

//get user_id
$user_id = $_SESSION["user_id"];

//get current time
$time = time(); 

//run query to create new note in notes
$sql = "INSERT INTO notes (`user_id`, `note`, `time`) VALUES ('$user_id', '', '$time')";
$result = mysqli_query($link, $sql);
if(!$result){
    echo 'error';
}else{
//    mysqli_insert_id returns the autogenerated id used in the last query
    echo mysqli_insert_id($link);
}
    
//show notes or alert message
?>